### ISSUE TITLE
Some methods are not included in EmoEngine and EmoState 

### ISSUE THREAD

**Issue by nadunindunil** [Emotiv/advanced-sdk#1]
PerformanceMetricEmoStateUpdatedEventHandler is not included in EmoEngine 
Also few I couldn't find some functions from EmoState 
could you please help me?

**Comment by duytan90** [comment]
What library version that you are using @nadunindunil?
Examples here on advanced-sdk that covers EEG and Performance Metrics need Premium SDK to run.
https://www.emotiv.com/sdk-premium-edition-application-form/

**Comment by nadunindunil** [comment]
@duytan90 thank you very much for reply.
That's must be the reason I was using the community edition. 
in addition to that, I have a question about performance metric.
- is it really working or do I have to use a raw data analysis of brain waves to identify states like excitement.
(community SDK says it's deprecated, hope not deprecated version included in premium version)
- What kind of factors do they consider when providing the premium version.

**Comment by duytan90** [comment]
@nadunindunil, The Performance Metrics example does return scores (https://github.com/Emotiv/advanced-sdk/blob/master/examples/C%2B%2B/PerformanceMetricsDemo/PerformanceMetricsDemo.cpp#L160), that could be analyzed and helpful for you.
I guess you applied the application form. I afraid that I can't tell how to be qualified to get the Premium SDK, maybe it depends on your purpose.

**Comment by nadunindunil** [comment]
@duytan90 thank you very much! 
that was really helpful. 👍
