### ISSUE TITLE
emotiv-matlab connection

### ISSUE THREAD

**Issue by masoudmaleki** [Emotiv/advanced-sdk#2]
hello 
i can not connect emotiv to matlab. when i run the eeglogger ihave this error: (https://cloud.githubusercontent.com/assets/24210292/20650719/fb0a019c-b4dd-11e6-91ce-40376861045e.jpg)

i used these:
Emotiv SDK Premium Edition v3.3.3
Emotiv Xavier ControlPanel v3.1.19
Emotiv Xavier TestBench v3.1.19
Emotiv EPOC Control Panel v2.0.0.21

please help me
thank you

**Comment by hoangphamemotiv** [comment]
Hi @masoudmaleki
i responed to you at: 
https://github.com/Emotiv/community-sdk/issues/144

**Comment by masoudmaleki** [comment]
i saw it. thank you so much. i will try it. 

    On Monday, November 28, 2016 12:13 PM, Pham Hoang <notifications@github.com> wrote:
 

 Closed #2.—
